import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { readSessionToken } from "@/lib/auth/session-cookie";
import { themeOfSessionToken } from "@/lib/settings/theme";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  // 테마(8h · F-12-03) — 첫 페인트 전에 정한다. 계정의 값을 서버가 첫 HTML 에 싣는다(로그인 전은 system · `settings/theme.ts`).
  // 세션 쿠키를 읽으므로 모든 화면이 요청 때 그려진다 — 화면들이 이미 세션을 읽어 그렇게 그려지고 있다.
  const theme = await themeOfSessionToken(await readSessionToken());
  return (
    <html
      lang="en"
      data-theme={theme}
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
